// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisLV-bvDjUiNONmXX266o_XkFSHIwOCk',
    appId: '1:460576204648:web:8b2c7555c1305327b558dd',
    messagingSenderId: '460576204648',
    projectId: 'baatain-1e5f3',
    authDomain: 'baatain-1e5f3.firebaseapp.com',
    storageBucket: 'baatain-1e5f3.appspot.com',
    measurementId: 'G-2JHBXNG3JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjy6Czq3pGviOhmRZiCeUPqe4_ZkxVUwE',
    appId: '1:460576204648:android:4bea4a309da3c3bab558dd',
    messagingSenderId: '460576204648',
    projectId: 'baatain-1e5f3',
    storageBucket: 'baatain-1e5f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0KJBu8j2zc9WU5DkvQ6cqIwTDWc5ZSg',
    appId: '1:460576204648:ios:7e486ee86d79a1f1b558dd',
    messagingSenderId: '460576204648',
    projectId: 'baatain-1e5f3',
    storageBucket: 'baatain-1e5f3.appspot.com',
    iosClientId: '460576204648-qk0e44q40du1t756lg5ghbv1829c2h1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.baatain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0KJBu8j2zc9WU5DkvQ6cqIwTDWc5ZSg',
    appId: '1:460576204648:ios:bf7344f3deb1cf43b558dd',
    messagingSenderId: '460576204648',
    projectId: 'baatain-1e5f3',
    storageBucket: 'baatain-1e5f3.appspot.com',
    iosClientId: '460576204648-76c9mc5s9o8sm4l92fru7mg0gku7o89u.apps.googleusercontent.com',
    iosBundleId: 'com.example.baatain.RunnerTests',
  );
}
